{{- if .Values.ankrobes.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "transcrobes.ankrobes.fullname" . }}
  labels:
    {{- include "transcrobes.ankrobes.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.ankrobes.replicaCount }}
  {{- if .Values.ankrobes.strategy }}
  strategy:
{{ toYaml .Values.ankrobes.strategy | indent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "transcrobes.ankrobes.matchLabels" . | nindent 6 }}
  template:
    metadata:
    {{- if .Values.ankrobes.podAnnotations }}
      annotations:
{{ toYaml .Values.ankrobes.podAnnotations | indent 8 }}
    {{- end }}
      labels:
        {{- include "transcrobes.ankrobes.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ template "transcrobes.name" . }}-{{ .Values.ankrobes.name }}
          image: "{{ .Values.ankrobes.image.repository }}:{{ .Values.ankrobes.image.tag }}"
          imagePullPolicy: {{ .Values.ankrobes.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.ankrobes.application.listenPort }}
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          #     periodSeconds: {{ .Values.ankrobes.readiness.periodSeconds }}
          #     initialDelaySeconds: {{ .Values.ankrobes.readiness.initialDelaySeconds }}
          #     timeoutSeconds: {{ .Values.ankrobes.readiness.timeoutSeconds }}
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          #     periodSeconds: {{ .Values.ankrobes.readiness.periodSeconds }}
          #     initialDelaySeconds: {{ .Values.ankrobes.readiness.initialDelaySeconds }}
          #     timeoutSeconds: {{ .Values.ankrobes.readiness.timeoutSeconds }}
          env:
            {{- range $key, $value := .Values.ankrobes.extraEnv }}
            - name: {{ $key }}
              value: {{ $value }}
            {{- end }}
            - name: PYTHONUNBUFFERED  # MUST put or no logs printed to kube, but probably should be in values
              value: "0"

            # All these values are passed via Kubernetes/Helm
            - name: ANKISYNCD_DB_HOST
              value: "{{ .Values.postgresql.fullnameOverride }}"
            - name: ANKISYNCD_DB_PORT
              value: "5432"  # TODO: hard-coded for the moment
            - name: ANKISYNCD_DB_NAME
              value: "{{ .Values.postgresql.postgresqlDatabase }}"
            - name: ANKISYNCD_DB_USER
              value: "{{ .Values.postgresql.postgresqlUsername }}"
            - name: ANKISYNCD_DB_PASSWORD
              value: "{{ .Values.postgresql.postgresqlPassword }}"
            - name: ANKISYNCD_HOST
              value: "{{ .Values.ankrobes.application.listenAddress }}"
            - name: ANKISYNCD_PORT
              value: "{{ .Values.ankrobes.application.listenPort }}"
            - name: ANKISYNCD_DATA_ROOT
              value: "{{ .Values.ankrobes.persistence.dataRoot }}"

      {{- if .Values.ankrobes.persistence.enabled }}
          volumeMounts:
          - mountPath: "{{ .Values.ankrobes.persistence.dataRoot }}"
            name: {{ include "transcrobes.ankrobes.fullname" . }}
      volumes:
        - name: {{ include "transcrobes.ankrobes.fullname" . }}
          persistentVolumeClaim:
            claimName: {{ include "transcrobes.ankrobes.fullname" . }}
      {{- end }}

      restartPolicy: Always
status: {}
{{- end }}
