{{- if .Values.ankrobes.enabled -}}
{{- $fullName := include "transcrobes.ankrobes.fullname" . -}}
{{- $ingressPath := .Values.ankrobes.ingress.path -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: {{ .Values.nginxingress.controller.ingressClass }}
    certmanager.k8s.io/cluster-issuer: {{ .Values.ankrobes.ingress.tls.issuer }}
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: {{ .Values.ankrobes.ingress.maxBodySize }}
  name: {{ include "transcrobes.ankrobes.fullname" . }}
  labels:
    {{- include "transcrobes.ankrobes.labels" . | nindent 4 }}

spec:
{{- if .Values.ankrobes.ingress.tls.enabled }}
  tls:
    - hosts:
      {{- range .Values.ankrobes.hosts }}
        - {{ . }}
      {{- end }}
      secretName: {{ .Values.ankrobes.ingress.tls.secretName }}
{{- end }}
  rules:
  {{- range .Values.ankrobes.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ $ingressPath }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: http
  {{- end }}
{{- end }}
